server:
  port: 8761

spring:
  application:
    name: discovery-service
  logging:
    level:
      org.springframework: WARN
      org.hibernate: WARN

eureka:
  numberRegistrySyncRetries: 1
  instance:
    preferIpAddress: true
    hostname: discovery-service
  client:
    registryFetchIntervalSeconds: 5
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/
    server:
      enable-self-preservation: false

management:
  security:
    enabled: false