server:
  port: 8762
spring:
  application:
    name: gateway-service
  logging:
    level:
      ROOT: INFO
      org.springframework.web: DEBUG
      org.hibernate: DEBUG
  zipkin:
    locator:
      discovery:
        enabled: true
      base-url: ${ZIPKIN_URL}
  sleuth:
    sampler:
      probability: 1

eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URL}
    registerWithEureka: true
    fetchRegistry: true
  instance:
    instanceId: ${spring.application.name}:${random.value}
    leaseRenewalIntervalInSeconds: 5
    preferIpAddress: true

management:
  security:
    enabled: false

zuul:
  routes:
    new:
      path: /news/**
      serviceId: new-service
      stripPrefix: false
    author:
      path: /authors/**
      serviceId: author-service
      stripPrefix: false
    category:
      path: /categories/**
      serviceId: category-service
      stripPrefix: false