server:
  port: 9411

spring:
  application:
    name: zipkin-service
  logging:
    level:
      org.springframework: DEBUG

eureka:
  instance:
    preferIpAddress: true
    instanceId: ${spring.application.name}:${random.value}
    leaseRenewalIntervalInSeconds: 5
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URL}

management:
  security:
    enabled: false

ribbon:
  eureka:
    enabled: true